### Numpy and Pytorch basics

Some of the sources used for this notebook

https://jhui.github.io/2018/02/09/PyTorch-Basic-operations/

http://cs231n.github.io/python-numpy-tutorial/

https://machinelearningmastery.com/index-slice-reshape-numpy-arrays-machine-learning-python/



In [24]:
import numpy as np
import torch
from PIL import Image

In [5]:
# get numpy version
np.version.version

'1.15.2'

In [2]:
# get pytorch version
print(torch.__version__)

1.0.0.dev20181019


### Numpy Arrays

Create 2D Array

Note we need to use two brackes ie [[..][..]]

In [8]:
a = np.array([[1,4,5],[2,7,4]])
a.shape

(2, 3)

In [ ]:
3D and 4D arrays

In [9]:
b = np.array([[1,4,5],[2,7,4],[8,9,10]])
b.shape

(3, 3)

In [16]:
a = np.zeros((2,2))   
a

array([[0., 0.],
       [0., 0.]])

In [18]:
b = np.ones((2,2,2))    
b

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [19]:
# array of constants
c = np.full((2,2), 42)  
c

array([[42, 42],
       [42, 42]])

In [13]:
#Identity matrix
d = np.eye(2)  
d

array([[1., 0.],
       [0., 1.]])

In [12]:
e = np.random.random((2,2))
e

array([[0.42487278, 0.92113314],
       [0.26282134, 0.16494706]])

In [15]:
#Transpose
e.T

array([[0.42487278, 0.26282134],
       [0.92113314, 0.16494706]])

### Arrays from lists

In [37]:
e = [[34,56,65],[23,55,32],[12,2,84]]
e, type(e)

([[34, 56, 65], [23, 55, 32], [12, 2, 84]], list)

In [38]:
e = np.array(e)
e, type(e)

(array([[34, 56, 65],
        [23, 55, 32],
        [12,  2, 84]]), numpy.ndarray)

### Slicing

In [39]:
#All rows, all except last column
f = e[:,:-1]
f, f.shape

(array([[34, 56],
        [23, 55],
        [12,  2]]), (3, 2))

In [40]:
#first row all columns
f = e[0,:]
f

array([34, 56, 65])

In [42]:
#all rows, last column
f = e[:,-1]
f

array([65, 32, 84])

### Split - eg for train and test

[start:stop:step]

In [48]:
#split on (zero indexed) row number
split = 2
train = e[:split,:]
train.shape, train

((2, 3), array([[34, 56, 65],
        [23, 55, 32]]))

In [49]:
test = e[split:,:]
test.shape, test

((1, 3), array([[12,  2, 84]]))

In [51]:
# get the first 2 rows and columns 1 and 2
b = e[:2, 1:3]
b

array([[56, 65],
       [55, 32]])

### Reshaping

In [52]:
e.shape

(3, 3)

In [53]:
h = e.reshape((e.shape[0], e.shape[1], 1))

In [54]:
h.shape

(3, 3, 1)

In [55]:
h

array([[[34],
        [56],
        [65]],

       [[23],
        [55],
        [32]],

       [[12],
        [ 2],
        [84]]])

In [62]:
h = e.reshape((1, -1))

In [63]:
h.shape

(1, 9)

In [64]:
h

array([[34, 56, 65, 23, 55, 32, 12,  2, 84]])

### pytorch dot products

In [65]:
n=100
x = torch.ones(n,2) 
x[:,0].uniform_(-1.,1)
x[:5]

tensor([[-0.5134,  1.0000],
        [-0.6057,  1.0000],
        [ 0.7419,  1.0000],
        [ 0.1915,  1.0000],
        [-0.5254,  1.0000]])

In [89]:
# 2x3: A uniform distributed random matrix with range [0, 1]
v = torch.Tensor(2, 3).uniform_(0, 1)

In [90]:
v.shape, x.shape

(torch.Size([2, 3]), torch.Size([100, 2]))

matrix 1 rows must be same size as matrix 2 columns

In [91]:
xv = x.mm(v) # computes A.B (matrix multiplication)
xv.shape, xv[0]

(torch.Size([100, 3]), tensor([-0.0672,  0.0042,  0.4846]))

In [92]:
xv = torch.mm(x, v)
xv.shape, xv[0]

(torch.Size([100, 3]), tensor([-0.0672,  0.0042,  0.4846]))

In [93]:
xv = x@v
xv.shape, xv[0]

(torch.Size([100, 3]), tensor([-0.0672,  0.0042,  0.4846]))

### hadamard (elementwise) product

In [95]:
y = torch.Tensor(2, 3).uniform_(0, 10)
z = torch.Tensor(2, 3).uniform_(10, 100)
y, z

(tensor([[4.0415, 3.7547, 8.6553],
         [4.4429, 0.8730, 4.0553]]), tensor([[39.3618, 59.9290, 77.3383],
         [33.4531, 88.1694, 56.3550]]))

In [97]:
yz = y * z 
yz.shape; yz

tensor([[159.0811, 225.0157, 669.3827],
        [148.6297,  76.9733, 228.5387]])